# ==========================================
# ESTÁGIO 1: BUILDER
# ==========================================
FROM python:3.11-slim AS builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./

ENV UV_COMPILE_BYTECODE=1
# Forçamos o uv a criar o ambiente num local blindado do SO
ENV UV_PROJECT_ENVIRONMENT="/opt/venv"

RUN uv sync --frozen --no-dev --no-install-project

# ==========================================
# ESTÁGIO 2: FINAL
# ==========================================
FROM python:3.11-slim

# Transferimos o ambiente blindado
COPY --from=builder /opt/venv /opt/venv

# Adicionamos o ambiente ao PATH
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app
COPY . .

EXPOSE 9000

WORKDIR /app/src/system
CMD ["python", "server.py"]