FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y iproute2 && rm -rf /var/lib/apt/lists/*

# Copy environment file
COPY env_cuda_latest.yaml .

# Create Conda environment
RUN conda env create -f env_cuda_latest.yaml && \
    conda clean -afy && \
    pip cache purge && \
    rm -rf /tmp/* /var/tmp/*

# Set working directory
WORKDIR /app

# Copy the application code
COPY . .

# Set the environment path
ENV PATH /opt/conda/envs/pfllib/bin:$PATH

# Define the entrypoint
CMD ["python", "-m", "src.system.client"]