version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
      args:
        - NO_CACHE=true
    container_name: fl-server
    ports:
      - "9090:9090"
    command: ["python", "server.py", "--dataset", "MNIST", "--clients-per-round", "3"]
    networks:
      - docker-tc
    # Adicionando labels para o docker-tc no servidor
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.limit=1mbit" # Limita a banda para 1 Mbit/s
      - "com.docker-tc.delay=100ms" # Adiciona um atraso de 100ms

  client: &client
    build:
      context: .
      dockerfile: dockerfile.client
      args:
        - NO_CACHE=true
    image: fl-client-image  # Nome fixo para a imagem
    depends_on:
      - server
    networks:
      - docker-tc
    # Adicionando labels para o docker-tc nos clientes
    labels:
      - "com.docker-tc.enabled=1"
      - "com.docker-tc.loss=10%" # Introduz 10% de perda de pacotes
networks:
  docker-tc:
    driver: bridge
