version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
      args:
        - NO_CACHE=true
    container_name: fl-server
    ports:
      - "9090:9090"
    command: ["python", "server.py", "--dataset", "MNIST", "--clients-per-round", "2"]
    networks:
      - fl-network

  client: &client
    build:
      context: .
      dockerfile: dockerfile.client
      args:
        - NO_CACHE=true
    image: fl-client-image
    depends_on:
      - server
    networks:
      - fl-network

  client-0:
    <<: *client
    container_name: fl-client-0
    command: ["python", "client.py", "--client-idx", "0", "--host", "fl-server", "--dataset", "MNIST"]

  client-1:
    <<: *client
    container_name: fl-client-1
    command: ["python", "client.py", "--client-idx", "1", "--host", "fl-server", "--dataset", "MNIST"]

networks:
  fl-network:
    driver: bridge
