version: '3.8'

networks:
  puma_default:
    driver: bridge

services:
  server:
    image: fl_server:latest
    container_name: puma-server
    hostname: server
    ports:
      - "9000:9000"
    # Mount logs so you can see them on your host machine
    volumes:
      - ./fl_logs:/app/fl_logs
    command: python -m src.system.server --port 9000 --clients-per-round 3 --dataset MNIST
    networks:
      - puma_default

  client_0:
    image: fl_client:latest
    container_name: puma-client_000
    depends_on:
      - server
    command: python -m src.system.client --host server --port 9000 --client-idx 0 --dataset MNIST
    networks:
      - puma_default
  client_1:
    image: fl_client:latest
    container_name: puma-client_001
    depends_on:
      - server
    command: python -m src.system.client --host server --port 9000 --client-idx 1 --dataset MNIST
    networks:
      - puma_default
  client_2:
    image: fl_client:latest
    container_name: puma-client_002
    depends_on:
      - server
    command: python -m src.system.client --host server --port 9000 --client-idx 2 --dataset MNIST
    networks:
      - puma_default
